# Generated by Django 4.0.6 on 2022-07-28 08:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('OWNER', 'Owner'), ('SELLER', 'Seller'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=15)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.useraccount')),
            ],
            options={
                'permissions': [('add_mobile', 'add mobile'), ('delete_mobile', 'delete mobile'), ('update_mobile', 'update mobile'), ('show_mobile', 'show mobile'), ('inactive_mobile', 'inactive mobile')],
                'proxy': False,
            },
            bases=('users.useraccount',),
            managers=[
                ('objects', users.managers.OwnerManager()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.useraccount')),
                ('mobiles', models.ManyToManyField(to='products.mobile')),
            ],
            options={
                'permissions': [('show_mobile', 'show mobile'), ('inactive_mobile', 'inactive mobile')],
                'proxy': False,
            },
            bases=('users.useraccount',),
            managers=[
                ('objects', users.managers.SellerManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.useraccount')),
                ('wallet', models.FloatField(default=1000.0)),
                ('purchases', models.ManyToManyField(to='products.mobile')),
            ],
            options={
                'permissions': [('buy_mobile', 'buy mobile'), ('show_mobile', 'show mobile')],
                'proxy': False,
            },
            bases=('users.useraccount',),
            managers=[
                ('objects', users.managers.CustomerManager()),
            ],
        ),
    ]
