# Generated by Django 4.0.6 on 2022-08-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'permissions': [('add_mobile', 'add mobile'), ('delete_mobile', 'delete mobile'), ('update_mobile', 'update mobile'), ('show_mobile', 'show mobile'), ('inactive_mobile', 'inactive mobile'), ('buy_mobile', 'buy mobile')]},
        ),
    ]
