# Generated by Django 4.0.6 on 2022-08-02 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.owner'),
            preserve_default=False,
        ),
    ]
